#!/usr/bin/env python3
"""Selected Max-stable pilot/Linear/Nonlinear-gate shared-NPE comparison.

Every arm receives the same complete datasets, shared data-only pilot, NPE
architecture, optimizer, and seed.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor
import csv
import hashlib
import json
import multiprocessing as mp
from pathlib import Path
import time
from typing import Any

import numpy as np
import torch

from maxstable_rainfall79.core import (
    composite_newton_pilot,
    compute_annual_features,
    jsonable,
    latin_hypercube,
    latent_to_physical,
    load_stage1_checkpoint,
    make_annual_pair_feature_function,
    physical_to_unit,
    SELECTED_PROTOCOL_VERSION,
    simulate_complete_dataset,
    stratified_pair_subdesign,
    transform_pair_inputs,
    transform_inputs,
    unit_to_physical,
)


PILOT_ONLY_LABEL = "shared composite pilot only + shared NPE"
LINEAR_LABEL = "ours linear full-dataset score + shared NPE"
POSITIVE_ANCHOR_LABEL = (
    "ours raw positive(s,anchor)-local-gate full-dataset score + shared NPE"
)
FAIR_METHOD_LABELS = {
    "pilot": PILOT_ONLY_LABEL,
    "linear": LINEAR_LABEL,
    "positive_anchor": POSITIVE_ANCHOR_LABEL,
}
NPE_MODEL = "mdn"
CONTEXT_PROVENANCE_KEY = "context_provenance_json"
CONTEXT_PROVENANCE_SCHEMA_VERSION = 1


_SIMULATION_CONFIG = None


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def unknown_context_provenance(reason: str) -> dict[str, Any]:
    return {
        "schema_version": None,
        "status": "unknown_legacy_cache",
        "reason": str(reason),
    }


def decode_context_provenance(saved: Any) -> dict[str, Any]:
    """Read optional cache provenance without breaking pre-metadata caches."""

    if CONTEXT_PROVENANCE_KEY not in saved.files:
        return unknown_context_provenance(
            "cache predates embedded context-generation metadata"
        )
    raw = np.asarray(saved[CONTEXT_PROVENANCE_KEY])
    if raw.shape != ():
        raise ValueError("context provenance must be a scalar JSON string")
    try:
        value = json.loads(str(raw.item()))
    except (TypeError, ValueError, json.JSONDecodeError) as error:
        raise ValueError("context provenance is not valid JSON") from error
    if not isinstance(value, dict):
        raise ValueError("context provenance must decode to an object")
    if (
        value.get("schema_version") is None
        and value.get("status") == "unknown_legacy_cache"
    ):
        return value
    if value.get("schema_version") != CONTEXT_PROVENANCE_SCHEMA_VERSION:
        raise ValueError(
            "unsupported context provenance schema: "
            f"{value.get('schema_version')!r}"
        )
    if value.get("status") != "known":
        raise ValueError("versioned context provenance must have status='known'")
    return value


def validate_reused_context_provenance(
    provenance: dict[str, Any],
    *,
    stage1_checkpoint_sha256: str,
    methods: tuple[str, ...],
    n_train: int,
    n_test: int,
) -> bool:
    """Validate versioned provenance; legacy unknown metadata remains usable."""

    if provenance.get("status") == "unknown_legacy_cache":
        return False
    expected_sha = provenance.get("stage1", {}).get("checkpoint_sha256")
    if expected_sha != str(stage1_checkpoint_sha256):
        raise ValueError(
            "saved contexts were generated by a different Stage-1 checkpoint: "
            f"cache={expected_sha!r}, current={stage1_checkpoint_sha256!r}"
        )
    if provenance.get("method_labels") != list(methods):
        raise ValueError("saved context provenance has incompatible method labels")
    simulation = provenance.get("simulation", {})
    if int(simulation.get("n_train", -1)) != int(n_train) or int(
        simulation.get("n_test", -1)
    ) != int(n_test):
        raise ValueError("saved context provenance has incompatible row counts")
    return True


def make_context_provenance(
    args: argparse.Namespace,
    stage1: dict[str, Any],
    methods: tuple[str, ...],
    stage1_checkpoint_sha256: str,
) -> dict[str, Any]:
    pilot_design = stratified_pair_subdesign(
        stage1["design"],
        int(args.pilot_pairs_per_group),
        int(args.pilot_pair_seed),
    )
    pairs_per_group = int(args.pilot_pairs_per_group)
    return {
        "schema_version": CONTEXT_PROVENANCE_SCHEMA_VERSION,
        "status": "known",
        "producer": "code/runners/run_stage2.py",
        "stage1": {
            "checkpoint_sha256": str(stage1_checkpoint_sha256),
            "protocol_version": str(stage1.get("protocol_version")),
        },
        "method_labels": list(methods),
        "simulation": {
            "n_train": int(args.n_train),
            "n_test": int(args.n_test),
            "seed": int(args.simulation_seed),
            "train_dataset_seed_offset": int(args.simulation_seed) + 10_000,
            "test_dataset_seed_offset": int(args.simulation_seed) + 10_000_000,
            "workers": int(args.simulation_workers),
        },
        "pilot": {
            "full_pair_count": int(len(stage1["design"].pairs)),
            "pairs_per_group": pairs_per_group,
            "selected_pair_count": int(len(pilot_design.pairs)),
            "pair_selection_seed": (
                None if pairs_per_group == 0 else int(args.pilot_pair_seed)
            ),
            "pair_selection": (
                "all pairs"
                if pairs_per_group == 0
                else "fixed random sample within every distance/angle group"
            ),
            "iterations": int(args.pilot_iterations),
            "batch_size": int(args.pilot_batch_size),
            "n_starts": int(args.pilot_n_starts),
            "n_refine_starts": int(args.pilot_n_refine_starts),
            "start_radius": float(args.pilot_start_radius),
            "backtracking_steps": int(args.pilot_backtracking_steps),
            "tolerance": float(args.pilot_tolerance),
        },
        "feature_evaluation": {
            "feature_chunk_size": int(args.feature_chunk_size),
            "score_batch_size": int(args.score_batch_size),
        },
    }


def pilot_generation_protocol(provenance: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "full_pair_count",
        "pairs_per_group",
        "selected_pair_count",
        "pair_selection_seed",
        "pair_selection",
        "iterations",
        "n_starts",
        "n_refine_starts",
        "start_radius",
        "backtracking_steps",
        "tolerance",
    )
    if provenance.get("status") != "known":
        return {key: "unknown" for key in keys}
    pilot = provenance.get("pilot", {})
    missing = [key for key in keys if key not in pilot]
    if missing:
        raise ValueError(f"context provenance is missing pilot fields: {missing}")
    return {key: pilot[key] for key in keys}


def context_cache_protocol(
    provenance: dict[str, Any], *, reused: bool, validated: bool
) -> dict[str, Any]:
    return {
        "mode": "reused" if reused else "generated",
        "generation_parameters_source": (
            "embedded_cache_metadata"
            if reused and validated
            else ("unknown_legacy_cache" if reused else "current_run")
        ),
        "stage1_checkpoint_match": True if validated else "unknown",
        "provenance": provenance,
    }


def _initialize_simulation_worker(config: Any) -> None:
    global _SIMULATION_CONFIG
    _SIMULATION_CONFIG = config


def _simulate_indexed_dataset(item: tuple[int, np.ndarray, int]):
    index, value, seed_offset = item
    if _SIMULATION_CONFIG is None:
        raise RuntimeError("simulation worker was not initialized")
    return index, simulate_complete_dataset(
        value, _SIMULATION_CONFIG, int(seed_offset) + int(index)
    )


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def simulate_prior_table(
    rng: np.random.Generator,
    n: int,
    stage1: dict[str, Any],
    seed_offset: int,
    *,
    workers: int = 1,
) -> tuple[np.ndarray, np.ndarray]:
    config = stage1["config"]
    theta = latin_hypercube(
        rng, int(n), config.theta_dim, config.u_min, config.u_max
    )
    if int(workers) <= 1:
        datasets = []
        for index, value in enumerate(theta):
            datasets.append(
                simulate_complete_dataset(value, config, int(seed_offset) + index)
            )
            print(f"Stage-2 complete datasets: {index + 1}/{n}", flush=True)
    else:
        tasks = (
            (index, np.asarray(value, dtype=np.float64), int(seed_offset))
            for index, value in enumerate(theta)
        )
        datasets = [None] * int(n)
        with ProcessPoolExecutor(
            max_workers=int(workers),
            mp_context=mp.get_context("spawn"),
            initializer=_initialize_simulation_worker,
            initargs=(config,),
        ) as executor:
            for completed, (index, dataset) in enumerate(
                executor.map(_simulate_indexed_dataset, tasks, chunksize=1), start=1
            ):
                datasets[index] = dataset
                if completed == 1 or completed % 100 == 0 or completed == int(n):
                    print(
                        f"Stage-2 complete datasets: {completed}/{n} "
                        f"({workers} workers)",
                        flush=True,
                    )
    return theta, np.stack(datasets).astype(np.float32)


def predict_stage1(
    model: torch.nn.Module,
    score: np.ndarray,
    anchor: np.ndarray,
    *,
    device: str,
    batch_size: int,
) -> np.ndarray:
    output: list[np.ndarray] = []
    model.eval()
    with torch.no_grad():
        for start in range(0, len(score), int(batch_size)):
            stop = min(start + int(batch_size), len(score))
            output.append(
                model(
                    torch.as_tensor(
                        score[start:stop], dtype=torch.float32, device=device
                    ),
                    torch.as_tensor(
                        anchor[start:stop], dtype=torch.float32, device=device
                    ),
                )
                .cpu()
                .numpy()
            )
    return np.concatenate(output)


def predict_pair_stage1_streaming_many(
    stage1: dict[str, Any],
    datasets: np.ndarray,
    pilot_w: np.ndarray,
    models: dict[str, torch.nn.Module],
    *,
    device: str,
    feature_chunk_size: int,
    score_batch_size: int,
) -> dict[str, np.ndarray]:
    """Score several pair-local models from one shared feature construction."""

    config = stage1["config"]
    design = stage1["design"]
    _, batch_function = make_annual_pair_feature_function(config, design)
    output: dict[str, list[np.ndarray]] = {key: [] for key in models}
    for start in range(0, len(datasets), int(feature_chunk_size)):
        stop = min(start + int(feature_chunk_size), len(datasets))
        raw = compute_annual_features(
            pilot_w[start:stop],
            datasets[start:stop],
            config,
            design,
            chunk_size=stop - start,
            batch_function=batch_function,
            label="Stage-2 pair-local features at shared pilot",
        )
        score, anchor = transform_pair_inputs(
            raw, pilot_w[start:stop], stage1["stats"], design.group_ids
        )
        for key, model in models.items():
            output[key].append(
                predict_stage1(
                    model,
                    score,
                    anchor,
                    device=device,
                    batch_size=score_batch_size,
                )
            )
    return {key: np.concatenate(value) for key, value in output.items()}


def build_contexts(
    stage1: dict[str, Any],
    datasets: np.ndarray,
    args: argparse.Namespace,
    *,
    device: str,
) -> tuple[np.ndarray, dict[str, np.ndarray], dict[str, np.ndarray]]:
    config = stage1["config"]
    design = stage1["design"]
    pilot_design = stratified_pair_subdesign(
        design,
        int(args.pilot_pairs_per_group),
        int(args.pilot_pair_seed),
    )
    pilot_w, pilot_diagnostics = composite_newton_pilot(
        datasets,
        config,
        pilot_design,
        iterations=int(args.pilot_iterations),
        batch_size=int(args.pilot_batch_size),
        n_starts=int(args.pilot_n_starts),
        n_refine_starts=int(args.pilot_n_refine_starts),
        start_radius=float(args.pilot_start_radius),
        backtracking_steps=int(args.pilot_backtracking_steps),
        convergence_tolerance=float(args.pilot_tolerance),
        return_diagnostics=True,
    )
    if stage1.get("protocol_version") != SELECTED_PROTOCOL_VERSION:
        raise ValueError("Stage 1 does not match the selected two-arm protocol")
    method_keys = ("pilot", "linear", "positive_anchor")
    predictions = predict_pair_stage1_streaming_many(
        stage1,
        datasets,
        pilot_w,
        {key: stage1["models"][key] for key in method_keys if key != "pilot"},
        device=device,
        feature_chunk_size=int(args.feature_chunk_size),
        score_batch_size=int(args.score_batch_size),
    )
    contexts = {
        FAIR_METHOD_LABELS[key]: (
            pilot_w.astype(np.float32)
            if key == "pilot"
            else np.concatenate((pilot_w, predictions[key]), axis=1).astype(np.float32)
        )
        for key in method_keys
    }
    if contexts[PILOT_ONLY_LABEL].shape != (len(datasets), 3):
        raise RuntimeError("bad pilot-only context shape")
    for label in (LINEAR_LABEL, POSITIVE_ANCHOR_LABEL):
        if contexts[label].shape != (len(datasets), 6):
            raise RuntimeError(f"bad score context shape for {label}")
    if not all(np.all(np.isfinite(value)) for value in contexts.values()):
        raise RuntimeError("non-finite shared context")
    return pilot_w, pilot_diagnostics, contexts


def import_sbi():
    try:
        from sbi.inference import NPE
    except ImportError:
        from sbi.inference import SNPE as NPE
    try:
        from sbi.neural_nets import posterior_nn
    except ImportError:
        from sbi.utils.get_nn_models import posterior_nn
    from sbi.utils import BoxUniform

    return NPE, posterior_nn, BoxUniform


def train_npe(
    method: str,
    context: np.ndarray,
    theta: np.ndarray,
    config: Any,
    args: argparse.Namespace,
    *,
    device: str,
) -> dict[str, Any]:
    NPE, posterior_nn, BoxUniform = import_sbi()
    torch.manual_seed(int(args.npe_seed))
    if device.startswith("cuda"):
        torch.cuda.manual_seed_all(int(args.npe_seed))
    theta_unit = torch.as_tensor(
        physical_to_unit(theta, config), dtype=torch.float32
    )
    x = torch.as_tensor(context, dtype=torch.float32)
    density = posterior_nn(
        model=NPE_MODEL,
        z_score_theta="independent",
        z_score_x="independent",
        hidden_features=int(args.npe_hidden),
        num_components=int(args.npe_components),
    )
    prior = BoxUniform(
        low=torch.zeros(config.theta_dim, dtype=torch.float32, device=device),
        high=torch.ones(config.theta_dim, dtype=torch.float32, device=device),
    )
    inference = NPE(
        prior=prior,
        density_estimator=density,
        device=device,
        show_progress_bars=False,
    )
    started = time.time()
    estimator = inference.append_simulations(
        theta_unit, x, data_device="cpu"
    ).train(
        training_batch_size=int(args.npe_batch_size),
        learning_rate=float(args.npe_lr),
        max_num_epochs=int(args.npe_epochs),
        validation_fraction=float(args.validation_fraction),
        stop_after_epochs=int(args.stop_after_epochs),
    )
    posterior = inference.build_posterior(estimator)
    print(f"trained {method} NPE in {time.time() - started:.1f}s", flush=True)
    return {
        "method": method,
        "posterior": posterior,
        "device": device,
        "state_dict": posterior.posterior_estimator.state_dict(),
    }


def posterior_samples(
    fitted: dict[str, Any],
    context: np.ndarray,
    config: Any,
    n: int,
    seed: int,
) -> np.ndarray:
    torch.manual_seed(int(seed))
    if str(fitted["device"]).startswith("cuda"):
        torch.cuda.manual_seed_all(int(seed))
    x = torch.as_tensor(
        context, dtype=torch.float32, device=fitted["device"]
    )
    unit = (
        fitted["posterior"]
        .sample((int(n),), x=x)
        .detach()
        .cpu()
        .numpy()
    )
    return unit_to_physical(unit, config)


def summarize(
    rows: list[dict[str, Any]], methods: tuple[str, ...]
) -> list[dict[str, Any]]:
    output = []
    for method in methods:
        selected = [row for row in rows if row["method"] == method]
        error = np.asarray(
            [row["posterior_mean_error"] for row in selected], dtype=np.float64
        )
        row_summary = {
                "method": method,
                "n_test": len(selected),
                "posterior_mean_rmse_by_coordinate": np.sqrt(
                    np.mean(error**2, axis=0)
                ).tolist(),
                "posterior_mean_l2_rmse_to_generating_parameter": float(
                    np.sqrt(np.mean(np.sum(error**2, axis=1)))
                ),
                "posterior_mean_mae_by_coordinate": np.mean(
                    np.abs(error), axis=0
                ).tolist(),
                "marginal_90_coverage_by_coordinate": np.mean(
                    [row["covers90"] for row in selected], axis=0
                ).tolist(),
                "mean_90_width_by_coordinate": np.mean(
                    [row["width90"] for row in selected], axis=0
                ).tolist(),
                "pilot_converged_count": int(
                    sum(bool(row["pilot_converged"]) for row in selected)
                ),
                "pilot_boundary_count": int(
                    sum(bool(row["pilot_boundary"]) for row in selected)
                ),
            }
        for label, keep in (
            ("pilot_converged", lambda row: bool(row["pilot_converged"])),
            ("pilot_not_converged", lambda row: not bool(row["pilot_converged"])),
            ("pilot_interior", lambda row: not bool(row["pilot_boundary"])),
            ("pilot_boundary", lambda row: bool(row["pilot_boundary"])),
        ):
            subset = [row for row in selected if keep(row)]
            if subset:
                subset_error = np.asarray(
                    [row["posterior_mean_error"] for row in subset], dtype=np.float64
                )
                row_summary[f"{label}_n"] = len(subset)
                row_summary[f"{label}_joint_l2_rmse"] = float(
                    np.sqrt(np.mean(np.sum(subset_error**2, axis=1)))
                )
        output.append(row_summary)
    return output


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage1-checkpoint", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--n-train", type=int, default=10_000)
    parser.add_argument("--n-test", type=int, default=100)
    parser.add_argument("--simulation-seed", type=int, default=20260731)
    parser.add_argument("--simulation-workers", type=int, default=32)
    parser.add_argument("--pilot-iterations", type=int, default=12)
    parser.add_argument("--pilot-batch-size", type=int, default=32)
    parser.add_argument("--pilot-n-starts", type=int, default=15)
    parser.add_argument("--pilot-n-refine-starts", type=int, default=3)
    parser.add_argument("--pilot-start-radius", type=float, default=2.0)
    parser.add_argument("--pilot-backtracking-steps", type=int, default=6)
    parser.add_argument(
        "--pilot-tolerance",
        type=float,
        default=1e-3,
        help=(
            "Threshold used only to label/report pilot convergence; it does not "
            "change the computed pilot root or the NPE context."
        ),
    )
    parser.add_argument(
        "--pilot-pairs-per-group",
        type=int,
        default=25,
        help="pairs selected per distance bin for the shared rough MPLE pilot",
    )
    parser.add_argument("--pilot-pair-seed", type=int, default=20260819)
    parser.add_argument("--feature-chunk-size", type=int, default=4)
    parser.add_argument("--score-batch-size", type=int, default=128)
    parser.add_argument("--context-only", type=int, choices=(0, 1), default=0)
    parser.add_argument("--npe-hidden", type=int, default=64)
    parser.add_argument("--npe-components", type=int, default=8)
    parser.add_argument("--npe-batch-size", type=int, default=256)
    parser.add_argument("--npe-lr", type=float, default=5e-4)
    parser.add_argument("--npe-epochs", type=int, default=300)
    parser.add_argument("--validation-fraction", type=float, default=0.10)
    parser.add_argument("--stop-after-epochs", type=int, default=20)
    parser.add_argument("--npe-seed", type=int, default=54_000)
    parser.add_argument("--posterior-n", type=int, default=5_000)
    parser.add_argument("--posterior-seed", type=int, default=87_000)
    parser.add_argument(
        "--reuse-contexts",
        action="store_true",
        help="resume NPE fitting from output-dir/contexts.npz without resimulation",
    )
    args = parser.parse_args(argv)

    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    device = (
        "cuda"
        if args.device == "auto" and torch.cuda.is_available()
        else ("cpu" if args.device == "auto" else args.device)
    )
    stage1 = load_stage1_checkpoint(args.stage1_checkpoint, device)
    if stage1.get("protocol_version") != SELECTED_PROTOCOL_VERSION:
        raise ValueError("Stage 1 does not match the selected two-arm protocol")
    required = {"linear", "positive_anchor"}
    missing = required.difference(stage1.get("models", {}))
    if missing:
        raise ValueError(f"Stage-1 checkpoint is missing selected arms: {sorted(missing)}")
    methods = tuple(FAIR_METHOD_LABELS[key] for key in ("pilot", "linear", "positive_anchor"))
    stage1_checkpoint_sha256 = file_sha256(args.stage1_checkpoint)
    context_provenance: dict[str, Any]
    context_provenance_validated = False
    if args.reuse_contexts:
        context_path = output / "contexts.npz"
        label_path = output / "context_labels.json"
        if not context_path.exists() or not label_path.exists():
            raise FileNotFoundError(
                "--reuse-contexts requires contexts.npz and context_labels.json "
                f"in {output}"
            )
        saved_labels = json.loads(label_path.read_text(encoding="utf-8"))
        expected_labels = {str(i): method for i, method in enumerate(methods)}
        if saved_labels != expected_labels:
            raise ValueError(
                "saved context labels do not match the selected methods: "
                f"saved={saved_labels}, expected={expected_labels}"
            )
        with np.load(context_path, allow_pickle=False) as saved:
            context_provenance = decode_context_provenance(saved)
            theta_train = saved["theta_train"]
            theta_test = saved["theta_test"]
            pilot_train = saved["pilot_w_train"]
            pilot_test = saved["pilot_w_test"]
            train_contexts = {
                method: saved[f"train_context_{index}"]
                for index, method in enumerate(methods)
            }
            test_contexts = {
                method: saved[f"test_context_{index}"]
                for index, method in enumerate(methods)
            }
            pilot_diagnostics_train = {
                name[len("pilot_") : -len("_train")]: saved[name]
                for name in saved.files
                if name.startswith("pilot_") and name.endswith("_train")
            }
            pilot_diagnostics_test = {
                name[len("pilot_") : -len("_test")]: saved[name]
                for name in saved.files
                if name.startswith("pilot_") and name.endswith("_test")
            }
        if len(theta_train) != int(args.n_train) or len(theta_test) != int(args.n_test):
            raise ValueError(
                "saved context row counts do not match --n-train/--n-test: "
                f"{len(theta_train)}/{len(theta_test)} versus "
                f"{args.n_train}/{args.n_test}"
            )
        context_provenance_validated = validate_reused_context_provenance(
            context_provenance,
            stage1_checkpoint_sha256=stage1_checkpoint_sha256,
            methods=methods,
            n_train=len(theta_train),
            n_test=len(theta_test),
        )
        if not context_provenance_validated:
            print(
                "WARNING: reused context cache has no embedded generation metadata; "
                "simulation, pilot, feature, and originating Stage-1 provenance will "
                "be reported as unknown",
                flush=True,
            )
        print(f"Reusing saved Stage-2 contexts from {context_path}", flush=True)
    else:
        rng = np.random.default_rng(int(args.simulation_seed))
        theta_train, y_train = simulate_prior_table(
            rng,
            int(args.n_train),
            stage1,
            int(args.simulation_seed) + 10_000,
            workers=int(args.simulation_workers),
        )
        theta_test, y_test = simulate_prior_table(
            rng,
            int(args.n_test),
            stage1,
            int(args.simulation_seed) + 10_000_000,
            workers=int(args.simulation_workers),
        )
        pilot_train, pilot_diagnostics_train, train_contexts = build_contexts(
            stage1,
            y_train,
            args,
            device=device,
        )
        pilot_test, pilot_diagnostics_test, test_contexts = build_contexts(
            stage1,
            y_test,
            args,
            device=device,
        )
        context_provenance = make_context_provenance(
            args, stage1, methods, stage1_checkpoint_sha256
        )
        context_provenance_validated = True
    payload: dict[str, np.ndarray] = {
        "theta_train": theta_train.astype(np.float32),
        "theta_test": theta_test.astype(np.float32),
        "pilot_w_train": pilot_train.astype(np.float32),
        "pilot_w_test": pilot_test.astype(np.float32),
        CONTEXT_PROVENANCE_KEY: np.asarray(
            json.dumps(jsonable(context_provenance), sort_keys=True)
        ),
    }
    for key, value in pilot_diagnostics_train.items():
        payload[f"pilot_{key}_train"] = np.asarray(value)
    for key, value in pilot_diagnostics_test.items():
        payload[f"pilot_{key}_test"] = np.asarray(value)
    for index, method in enumerate(methods):
        payload[f"train_context_{index}"] = train_contexts[method]
        payload[f"test_context_{index}"] = test_contexts[method]
    np.savez_compressed(output / "contexts.npz", **payload)
    (output / "context_labels.json").write_text(
        json.dumps({str(i): m for i, m in enumerate(methods)}, indent=2),
        encoding="utf-8",
    )
    pilot_protocol = pilot_generation_protocol(context_provenance)
    protocol = {
        "one_complete_dataset": (
            f"({stage1['config'].n_years} iid annual fields, "
            f"{stage1['config'].n_sites} sites)"
        ),
        "stage1_checkpoint": str(args.stage1_checkpoint.resolve()),
        "stage1_checkpoint_role": (
            "current runtime configuration and parameter support; context-generation "
            "origin and match status are recorded under context_cache"
        ),
        "shared_data_only_pilot": True,
        "shared_stage2_datasets": True,
        "shared_npe_architecture_optimizer_and_seed": True,
        "fair_method_keys": ["pilot", "linear", "positive_anchor"],
        "context": "(pilot_w[3], full_dataset_score_w_at_pilot[3])",
        "true_parameter_role": "NPE target and held-out calibration only",
        "true_parameter_in_context": False,
        "true_full_likelihood_or_score_used": False,
        "headline_limit": (
            "Max-stable exact posterior is unavailable; the reported held-out "
            "metrics are calibration/error to the generating parameter, not "
            "posterior-approximation error to an exact posterior."
        ),
        "n_train": int(args.n_train),
        "n_test": int(args.n_test),
        "context_cache": context_cache_protocol(
            context_provenance,
            reused=bool(args.reuse_contexts),
            validated=context_provenance_validated,
        ),
        "pilot": {
            **pilot_protocol,
            "projected_residual_median_train": float(
                np.median(pilot_diagnostics_train["projected_residual"])
            ),
            "projected_residual_median_test": float(
                np.median(pilot_diagnostics_test["projected_residual"])
            ),
            "failure_fraction_train": float(
                1.0 - np.mean(pilot_diagnostics_train["converged"])
            ),
            "failure_fraction_test": float(
                1.0 - np.mean(pilot_diagnostics_test["converged"])
            ),
            "boundary_fraction_train": float(
                np.mean(pilot_diagnostics_train["boundary"])
            ),
            "boundary_fraction_test": float(
                np.mean(pilot_diagnostics_test["boundary"])
            ),
            "fallback_fraction_train": float(
                np.mean(pilot_diagnostics_train["fallback"])
            ),
            "fallback_fraction_test": float(
                np.mean(pilot_diagnostics_test["fallback"])
            ),
        },
    }
    if bool(args.context_only):
        (output / "protocol.json").write_text(
            json.dumps(jsonable(protocol), indent=2), encoding="utf-8"
        )
        return

    fitted_npe = {
        method: train_npe(
            method,
            train_contexts[method],
            theta_train,
            stage1["config"],
            args,
            device=device,
        )
        for method in methods
    }
    for index, method in enumerate(methods):
        torch.save(
            {
                "method": method,
                "state_dict": fitted_npe[method]["state_dict"],
            },
            output / f"npe_{index}.pt",
        )
    rows: list[dict[str, Any]] = []
    for dataset_index in range(len(theta_test)):
        for method_index, method in enumerate(methods):
            samples = posterior_samples(
                fitted_npe[method],
                test_contexts[method][dataset_index],
                stage1["config"],
                int(args.posterior_n),
                int(args.posterior_seed) + dataset_index,
            )
            mean = samples.mean(axis=0)
            sd = samples.std(axis=0)
            lower, upper = np.quantile(samples, (0.05, 0.95), axis=0)
            truth = theta_test[dataset_index]
            rows.append(
                {
                    "test_index": dataset_index,
                    "method": method,
                    "u_true": truth.tolist(),
                    "posterior_mean": mean.tolist(),
                    "posterior_sd": sd.tolist(),
                    "q05": lower.tolist(),
                    "q95": upper.tolist(),
                    "posterior_mean_error": (mean - truth).tolist(),
                    "covers90": ((lower <= truth) & (truth <= upper)).tolist(),
                    "width90": (upper - lower).tolist(),
                    "pilot_raw_residual": float(
                        pilot_diagnostics_test["raw_residual"][dataset_index]
                    ),
                    "pilot_projected_residual": float(
                        pilot_diagnostics_test["projected_residual"][dataset_index]
                    ),
                    "pilot_converged": bool(
                        pilot_diagnostics_test["converged"][dataset_index]
                    ),
                    "pilot_boundary": bool(
                        pilot_diagnostics_test["boundary"][dataset_index]
                    ),
                    "pilot_fallback": bool(
                        pilot_diagnostics_test["fallback"][dataset_index]
                    ),
                }
            )
    summary = summarize(rows, methods)
    write_csv(
        output / "posterior_by_dataset.csv",
        [
            {
                **row,
                **{
                    key: json.dumps(value)
                    for key, value in row.items()
                    if isinstance(value, list)
                },
            }
            for row in rows
        ],
    )
    (output / "summary.json").write_text(
        json.dumps(jsonable(summary), indent=2), encoding="utf-8"
    )
    protocol["npe"] = {
        "model": NPE_MODEL,
        "hidden": int(args.npe_hidden),
        "components": int(args.npe_components),
        "batch_size": int(args.npe_batch_size),
        "seed": int(args.npe_seed),
    }
    (output / "protocol.json").write_text(
        json.dumps(jsonable(protocol), indent=2), encoding="utf-8"
    )
    print(json.dumps(jsonable(summary), indent=2), flush=True)


if __name__ == "__main__":
    main()
