#!/usr/bin/env python3
"""Compare NLSA's gain over ILSA (1, s) across Model 1 data-generating settings.

Reads runs/setting/s1_* and s2_* written by scripts/run_model1_setting_job.sh,
and the pooling-loss table from scripts/model1_pooling_loss.py, then writes
new_results/MODEL1_SETTINGS_TABLES.md. For the current setting it also pairs
ILSA (1, s) with the earlier s-only ILSA runs in runs/s1_sq0.20_* and
runs/s2_sq0.20_*, which share seeds, simulation banks and test datasets.

Gains are paired by Stage-1 seed: (NLSA - ILSA) / ILSA per seed, then averaged.
Negative values favour NLSA. SEs are over seeds only; they do not include
NPE-fit or test-bank variability.
"""
from __future__ import annotations

import csv
import json
import math
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs"
SETTING = RUNS / "setting"
OUT = ROOT / "new_results" / "MODEL1_SETTINGS_TABLES.md"
ARMS = ("linear", "radial", "stacked")
NAMES = {"pilot": "pilot only", "linear": "ILSA (1, s)", "radial": "NLSA gate", "stacked": "NLSA stacked"}


def arm_of(label: str) -> str | None:
    for prefix, arm in (("pilot-only", "pilot"), ("linear", "linear"), ("radial", "radial"), ("stacked", "stacked")):
        if label.startswith(prefix):
            return arm
    return None


def stage1_table(run: Path) -> dict[tuple[str, float], float]:
    rows = csv.DictReader((run / "score_summary_by_pi.csv").open())
    return {(arm_of(r["method"]), round(float(r["pi"]), 4)): float(r["std_mse"]) for r in rows if arm_of(r["method"])}


def stage2_table(run: Path) -> dict[tuple[str, float], float]:
    acc: dict[tuple[str, float], list[float]] = defaultdict(list)
    for r in csv.DictReader((run / "posterior_by_seed.csv").open()):
        arm = arm_of(r["method"])
        if arm:
            acc[(arm, round(float(r["pi_true"]), 4))].append(float(r["w1_to_exact"]))
    return {key: float(np.mean(v)) for key, v in acc.items()}


def discover() -> dict[str, dict]:
    settings: dict[str, dict] = {}
    for s1 in sorted(SETTING.glob("s1_*")):
        if not (s1 / "score_summary_by_pi.csv").exists():
            continue
        tag, seed = s1.name[3:].rsplit("_", 1)
        cfg = json.loads((s1 / "config.json").read_text())
        entry = settings.setdefault(tag, {"K": cfg["n_blocks"], "m": cfg["block_size"], "tau": cfg["tau"],
                                          "s1": {}, "s2": {}})
        entry["s1"][int(seed)] = stage1_table(s1)
        s2 = SETTING / f"s2_{tag}_{seed}"
        if (s2 / "posterior_by_seed.csv").exists():
            entry["s2"][int(seed)] = stage2_table(s2)
    return settings


def pooling_loss() -> dict[tuple[int, float, float], float]:
    path = SETTING / "pooling_loss_settings.csv"
    if not path.exists():
        return {}
    return {(int(r["block_size"]), round(float(r["tau"]), 4), round(float(r["pi"]), 4)): float(r["D"])
            for r in csv.DictReader(path.open())}


def paired(tables: dict[int, dict], arm: str, base: str, pis: list[float]) -> tuple[float, float, int]:
    """Mean over seeds of the per-seed relative change, pooling pis with equal weight."""
    rel = []
    for table in tables.values():
        if all((arm, p) in table and (base, p) in table for p in pis):
            a = np.mean([table[(arm, p)] for p in pis])
            b = np.mean([table[(base, p)] for p in pis])
            rel.append(a / b - 1.0)
    if not rel:
        return math.nan, math.nan, 0
    se = float(np.std(rel, ddof=1) / math.sqrt(len(rel))) if len(rel) > 1 else math.nan
    return float(np.mean(rel)), se, len(rel)


def mean_over_seeds(tables: dict[int, dict], arm: str, pi: float) -> float:
    vals = [t[(arm, pi)] for t in tables.values() if (arm, pi) in t]
    return float(np.mean(vals)) if vals else math.nan


def pct(x: float, se: float = math.nan) -> str:
    if math.isnan(x):
        return "—"
    return f"{100 * x:+.1f}%" + ("" if math.isnan(se) else f" ± {100 * se:.1f}")


def rankdata(x: list[float]) -> np.ndarray:
    order = np.argsort(x)
    ranks = np.empty(len(x))
    ranks[order] = np.arange(len(x))
    return ranks


def main() -> None:
    settings = discover()
    D = pooling_loss()
    L: list[str] = ["# Model 1 settings: NLSA gain over ILSA (1, s)", "",
                    "Generated by `scripts/summarize_setting_comparison.py`; do not edit by hand.",
                    "Relative changes are paired by Stage-1 seed; negative favours NLSA. ± is one SE over seeds.", ""]
    if not settings:
        L.append("No completed runs under runs/setting yet.")
        OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
        print("\n".join(L))
        return

    cells = []  # (D, gate gain, stacked gain) per setting x pi for the rank correlation
    for stage, key, metric in (("Stage 1", "s1", "standardized exact-score MSE"),
                               ("Stage 2", "s2", "W1 to the exact posterior")):
        L += [f"## {stage}: {metric}", ""]
        L += ["| setting | K | m | τ | seeds | π | D | ILSA (1, s) | gate | stacked | gate vs ILSA | stacked vs ILSA |",
              "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
        for tag, s in settings.items():
            tables = s[key]
            if not tables:
                continue
            pis = sorted({p for t in tables.values() for (arm, p) in t if arm == "linear"})
            for pi in pis + ["pooled"]:
                use = pis if pi == "pooled" else [pi]
                g, gse, n = paired(tables, "radial", "linear", use)
                st, sse, _ = paired(tables, "stacked", "linear", use)
                d = D.get((int(s["m"]), round(float(s["tau"]), 4), pi)) if pi != "pooled" else None
                if pi != "pooled" and key == "s1" and d is not None:
                    cells.append((d, g, st))
                vals = [np.mean([mean_over_seeds(tables, arm, p) for p in use]) for arm in ARMS]
                L.append(f"| {tag} | {s['K']} | {s['m']} | {s['tau']} | {n} | {pi} | "
                         f"{'—' if d is None else f'{d:.3f}'} | " + " | ".join(f"{v:.5f}" for v in vals)
                         + f" | {pct(g, gse)} | {pct(st, sse)} |")
        L.append("")

    if len(cells) >= 3:
        d, g, st = (np.array(c) for c in zip(*cells))
        rho_g = float(np.corrcoef(rankdata(list(d)), rankdata(list(g)))[0, 1])
        rho_s = float(np.corrcoef(rankdata(list(d)), rankdata(list(st)))[0, 1])
        L += ["## Does the Stage-1 gain track D?", "",
              f"Spearman correlation over {len(cells)} setting × π cells between D and the relative change "
              f"(more negative = larger NLSA gain): gate {rho_g:+.2f}, stacked {rho_s:+.2f}. "
              "A strongly negative value means larger pooling loss goes with larger NLSA gain.", ""]

    base = next((t for t in settings if t.startswith("base")), None)
    if base:
        L += ["## ILSA (1, s) against the earlier s-only ILSA, current setting", "",
              "| stage | π | seeds | s-only ILSA | ILSA (1, s) | change |", "|---|---:|---:|---:|---:|---:|"]
        for key, loader, old_name in (("s1", stage1_table, "s1_sq0.20_{}"), ("s2", stage2_table, "s2_sq0.20_{}")):
            new = settings[base][key]
            old = {}
            for seed in new:
                path = RUNS / old_name.format(seed)
                needed = "score_summary_by_pi.csv" if key == "s1" else "posterior_by_seed.csv"
                if (path / needed).exists():
                    old[seed] = loader(path)
            pis = sorted({p for t in new.values() for (arm, p) in t if arm == "linear"})
            for pi in pis:
                seeds = [s for s in new if s in old and ("linear", pi) in old[s]]
                if not seeds:
                    continue
                o = np.mean([old[s][("linear", pi)] for s in seeds])
                n_ = np.mean([new[s][("linear", pi)] for s in seeds])
                L.append(f"| {'Stage 1 std MSE' if key == 's1' else 'Stage 2 W1'} | {pi} | {len(seeds)} | "
                         f"{o:.5f} | {n_:.5f} | {pct(n_ / o - 1.0)} |")
        L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
